### ISSUE TITLE
[HTML] Deploy basic project - photocamera test

### ISSUE THREAD

**Issue by manuelalonge** [manuelalonge/team-four-webapp-frontend#118]
Deploy a simple basic project to experiment how the `capture` tag works (test for photocamera from mobile).

Time estimate: 0.30
Effective time: 0.10

Deadline: 29/01/2021
Actual finish date: 25/01/2021

@manuelalonge  ok task completed. We don't need the tag capture, we can remove it. If you want to check here, tell me if you see the possibility to choose camera as well. 

this is the link to check on mobile:
https://focused-poitras-cc13c7.netlify.app/

**Comment by manuelalonge** [comment]
@LucaBert89 can I close this issue?

**Comment by LucaBert89** [comment]
@manuelalonge have you test it on mobile? In my phone it works but I want to check if is different on yours! Then if it works, I'll fix the html project removing the capture tag

**Comment by manuelalonge** [comment]
@LucaBert89 sorry I did not see the comment with the link, I will take a look right now

**Comment by LucaBert89** [comment]
@manuelalonge no problem! Yes, It's just a test basic html, it's not our project..try to press choose file and tell me if you can choose to take a picture also instead of select an image from gallery..and if you take a picture, whether that picture'll be displayed or not

**Comment by manuelalonge** [comment]
@LucaBert89 it seems to be working, that's what happens when I click on that button
![366f81c5-6a16-43f3-8f39-d61a464ba84a](https://user-images.githubusercontent.com/48571023/105872746-07f72700-5ffb-11eb-9cf8-bc8c720ebac1.jpg)

**Comment by manuelalonge** [comment]
@LucaBert89 good stuff!

**Comment by manuelalonge** [comment]
@LucaBert89 also when I take the picture from my camera it is displayed. If you have some time could you please make a short video to explain to us how you did it? It could be good to learn. Thanks.
